"""Catálogo cerrado de códigos de error de la API — ADR-0013."""

from enum import StrEnum


class ErrorCode(StrEnum):
    DUPLICATE_IDEMPOTENT = "DUPLICATE_IDEMPOTENT"
    NOT_FOUND = "NOT_FOUND"
    UNAUTHENTICATED = "UNAUTHENTICATED"
    FORBIDDEN = "FORBIDDEN"
    ORIGIN_NOT_ALLOWED = "ORIGIN_NOT_ALLOWED"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    EMAIL_TAKEN = "EMAIL_TAKEN"
    USERNAME_TAKEN = "USERNAME_TAKEN"
    NAME_TAKEN = "NAME_TAKEN"
    PROFILE_IN_USE = "PROFILE_IN_USE"
    PASSWORD_CHANGE_REQUIRED = "PASSWORD_CHANGE_REQUIRED"
    CONFLICT = "CONFLICT"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    RATE_LIMITED = "RATE_LIMITED"
    INTERNAL_ERROR = "INTERNAL_ERROR"
