/**
 * @jest-environment node
 */
import fs from "node:fs";
import path from "node:path";
import { globSync } from "glob";

const ROOT = path.resolve(__dirname, "../../..");
const OPENAPI = path.resolve(ROOT, "../backend/openapi.json");
const GENERATED = path.join(ROOT, "src/types/api.generated.ts");

/**
 * ADR-0013. Mientras `backend/openapi.json` no exista (T2 en paralelo), estos
 * chequeos no tienen contra qué comparar y se saltean de forma VISIBLE
 * (`it.skip` aparece en el reporte). Apenas el backend publique el contrato,
 * se activan solos y fallan si `src/types/api.ts` provisorio sigue declarando
 * a mano algún schema — que es exactamente lo que se quiere.
 */
const hayContrato = fs.existsSync(OPENAPI);
const itConContrato = hayContrato ? it : it.skip;

describe("ADR-0013: tipos generados del OpenAPI", () => {
  itConContrato("src/types/ no redeclara ningún schema del backend", () => {
    const spec = JSON.parse(fs.readFileSync(OPENAPI, "utf8")) as {
      components?: { schemas?: Record<string, unknown> };
    };
    const generados = new Set(Object.keys(spec.components?.schemas ?? {}));
    const aMano = globSync("src/types/*.ts", {
      cwd: ROOT,
      ignore: "src/types/api.generated.ts",
    }).flatMap((f) =>
      [...fs.readFileSync(path.join(ROOT, f), "utf8").matchAll(/(?:interface|type)\s+(\w+)/g)].map(
        (m) => m[1],
      ),
    );
    expect(aMano.filter((n) => n !== undefined && generados.has(n))).toEqual([]);
  });

  itConContrato("el archivo generado existe y no fue editado a mano", () => {
    expect(fs.existsSync(GENERATED)).toBe(true);
    // openapi-typescript 7 escribe "Do not make direct changes to the file."; la
    // regex de la ADR (`do not (modify|edit) it by hand`) es de otro generador.
    expect(fs.readFileSync(GENERATED, "utf8")).toMatch(
      /auto-generated by openapi-typescript[\s\S]*do not (make direct changes|modify|edit)/i,
    );
  });

  it("el script gen:api apunta al artefacto del backend", () => {
    const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, "package.json"), "utf8")) as {
      scripts: Record<string, string>;
    };
    expect(pkg.scripts["gen:api"]).toBe(
      "openapi-typescript ../backend/openapi.json -o src/types/api.generated.ts",
    );
  });

  if (!hayContrato) {
    it("src/types/api.ts está marcado como PROVISORIO mientras no hay contrato", () => {
      expect(fs.readFileSync(path.join(ROOT, "src/types/api.ts"), "utf8")).toMatch(
        /^\/\/ PROVISORIO/,
      );
    });
  }
});
